### ISSUE TITLE
rake bench:* fails

### ISSUE THREAD

**Issue by dubek** [alexdowad/bit-twiddle#1]
```
$ rake bench:shift
Calculating -------------------------------------
#lshift32 on 32-bit Fixnum, small shift (x1000)
                    rake aborted!
NoMethodError: undefined method `lshift32' for 3555335789:Fixnum
/home/dmurik/world/bit-twiddle/bench/shift_bench.rb:12:in `block (4 levels) in <top (required)>'
/home/dmurik/world/bit-twiddle/bench/shift_bench.rb:12:in `each'
/home/dmurik/world/bit-twiddle/bench/shift_bench.rb:12:in `block (3 levels) in <top (required)>'
/home/dmurik/world/bit-twiddle/bench/shift_bench.rb:12:in `times'
/home/dmurik/world/bit-twiddle/bench/shift_bench.rb:12:in `block (2 levels) in <top (required)>'
/home/dmurik/.rvm/gems/ruby-2.3.0/gems/benchmark-ips-2.3.0/lib/benchmark/ips/job.rb:67:in `call_times'
/home/dmurik/.rvm/gems/ruby-2.3.0/gems/benchmark-ips-2.3.0/lib/benchmark/ips/job.rb:236:in `block in run_warmup'
/home/dmurik/.rvm/gems/ruby-2.3.0/gems/benchmark-ips-2.3.0/lib/benchmark/ips/job.rb:221:in `each'
/home/dmurik/.rvm/gems/ruby-2.3.0/gems/benchmark-ips-2.3.0/lib/benchmark/ips/job.rb:221:in `run_warmup'
/home/dmurik/.rvm/gems/ruby-2.3.0/gems/benchmark-ips-2.3.0/lib/benchmark/ips.rb:55:in `ips'
/home/dmurik/world/bit-twiddle/bench/shift_bench.rb:10:in `<top (required)>'
/home/dmurik/world/bit-twiddle/Rakefile:32:in `load'
/home/dmurik/world/bit-twiddle/Rakefile:32:in `block (2 levels) in <top (required)>'
/home/dmurik/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/dmurik/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => bench:shift
(See full trace by running task with --trace)
```

I changed the rake task to require `bit-twiddle/core_ext` and it seems to solve the problem, but I'm not sure if that's the correct fix (or to modify the benchmarks to use the `BitTwiddle.*` methods).

**Comment by alexdowad** [comment]
Thanks for pointing this out, I'll fix it.

**Comment by alexdowad** [comment]
Thanks, @dubek. The benchmarks should run properly now.

You'll find that the performance advantage to using `lshift32`, etc. is not very great. The most useful thing there is the arithmetic right shift, if you have an algorithm which needs one. (It's the same as the `>>>` operator in Java.)
